# Generated by Django 3.1.6 on 2021-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
