# Generated by Django 3.1.6 on 2021-03-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=30)),
                ('To', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
