# Generated by Django 3.1.6 on 2021-03-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('receiver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main.customer')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
